FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS api-build
WORKDIR /app/api

COPY api/api.csproj .
RUN dotnet restore
RUN dotnet tool restore

FROM node:18-alpine AS web-build
WORKDIR /app/web

COPY web/package.json web/package-lock.json web/.npmrc ./
RUN npm ci

COPY --from=api-build /app/api/swagger.json /app/web/src/api/swagger.json
COPY web/ .
RUN npm run codegen

