version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    volumes:
      - './api:/app/api'
      - '/app/api/bin'
      - '/app/api/obj'
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api-build
    command: dotnet watch

  web:
    image: node:18-alpine
    volumes:
      - './web:/app/web'
      - '/app/web/node_modules'
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web-build
    command: npm run dev

