version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '8099:8099'
    command: dotnet run

  web:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev

