
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: api-build

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: web-build

