version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    volumes:
      - './api:/app/api'
      - '/app/api/bin'
      - '/app/api/obj'
    working_dir: '/app/api'
    command: sh -c "dotnet restore && dotnet tool restore && dotnet watch"

  web:
    image: node:18-alpine
    volumes:
      - './web:/app/web'
      - '/app/web/node_modules'
    working_dir: '/app/web'
    command: sh -c "npm ci && npm run dev"

