version: '3.8'

services:
  api:
    ports:
      - '8099:8099'
    env_file: .env
    environment:
      - 'DOTNET_ROLL_FORWARD=LatestMajor'
    depends_on:
      - mysql
      - redis

  web:
    ports:
      - '8080:5173'
    env_file: .env
    depends_on:
      - api

  mysql:
    image: mysql:8.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABSE=${MYSQL_DATABASE}

  redis:
    image: redis:7.2.3-alpine
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}

